### ISSUE TITLE
[Feature Request] Replace Laravel as reference implementation

### ISSUE THREAD

**Issue by vandemars** [what-crud/vue-crud#33]
IMO, Laravel, per definition, is the opposite of the dynamic goals of this project and should be replaced as default/reference implementation.

For someone who never had to work with laravel before, it's a pain in the *** to untie the intricacies and understand whats going on. But on the other hand, it would be fairly easy for everyone experienced with laravel, to see through, say, a implementation using a basic PSR-7 framework.
Furthermore, i would say that 20% of all issues opened are directly or indirectly related to the unnecessary complexity of the current laravel integration respectively the lack of a unmistakably clear and intelligible-to-everyone reference implementation.

As an advancement that perfectly fits the idea behinde vue-crud, i recommend using [TreeQL (resp. PHP-CRUD-API)](https://github.com/mevdschee/php-crud-api) as it is almost the server-side equivalent of vue-crud. One single PHP file that auto-generates a RESTful API from an underlying Database including authentication/authorization, GraphQL-esque responses, middlewares, xsrf blocking, firewall and so on. 

If that is not suitable, for whatever reasons, i suggest improving the project by switching to [slim Framework](https://github.com/slimphp/Slim) for its simple yet powerful API building tools.
I would even prefer slim, cause i love to have the convenience (Router, Middleware, PSR-7, DI) without loosing complete control over whats going on or beeing forced to bloat my apps.
 
But, as both are based on similar concepts, both outpace laravel with ease.

Last not least, the whole backend could be excluded too, letting a demo implementation be written against fake data. Maybe this would be the most "readable" solution, as you dont have to comprehend the communication between front- and backend. But even if this would be the least convenient solution, i would prefer it over using a fat-framework like Laravel, if only because the only thing you learn from using Laravel is how to use Laravel.

A less emotional argument wanted?
Laravel footprint > 200 MB
Slim = 853 kB
PHP-CRUD-API > 260 kB

**Comment by szczepanmasny** [comment]
Hi, thanks for your comment.
You are absolutely right, I agree with you that Laravel is not good option for demonstrating vue-crud conception.

The problem is that when I started this project, I didn't know I would put it on github someday. I'm using Laravel in my work, and the projects I create are more extensive than the examples in the repository. And I think that Laravel works very well - it has ORM, database migration system and seeders, MVC, router, middleware, etc.
If I have time, I will try to prepare and share the API written in one of the tools provided by you.
