### ISSUE TITLE
Data not shown in ItemDetails Form

### ISSUE THREAD

**Issue by michigit-dev** [what-crud/vue-crud#55]
**Describe the bug**
Hi,
Bug: empty fields in itemDetails Form

**To Reproduce**
1. Go to 'Companies'
2. Open a item from data-table and remember the ID
3. no need to do anything just close it again
4. Go to 'Company Types' without doing anything go back to 'Companies' 
5. Open the same row from Data table the Form is empty

i use chrome browser

best regards

michi

**Comment by hizmarck** [comment]
I think that issue is related to #56

**Comment by szczepanmasny** [comment]
Hi,
Thanks for finding this bug.
I have solved this issue in this commit https://github.com/what-crud/vue-crud/commit/eae86bf62df344f16958676f8833609ee17be773
When user went back to the item which he watched previously app didn't react because it didn't catch any changes in stored item. I had to reset this item after table destroy.
@michigit-dev  Could you check if problem has been solved?
